# This file is auto-generated by scripts/codegen.ts.
# Do not edit by hand; re-run `bunx nx codegen ipyniivue`.
# Source: packages/niivue/src/NVControlBase.ts @ niivue 1.0.0-rc.12

# ruff: noqa
# mypy: ignore-errors

from __future__ import annotations

from typing import Any

import anywidget
import traitlets


_UNSET = object()
_JS_UNDEFINED = {"__ipyniivue_undefined__": True}


def _make_args(*values: Any) -> list[Any]:
    """Build JSON-safe JS call args while preserving omitted optionals."""
    trimmed = list(values)
    while trimmed and trimmed[-1] is _UNSET:
        trimmed.pop()
    return [_JS_UNDEFINED if value is _UNSET else value for value in trimmed]


# Set of event names that JS may dispatch to Python. The
# hand-written `widget.NiiVue.on()` method validates against this.
# Events that the JS template intentionally suppresses (high-frequency
# layout ticks like `canvasResize`) are filtered out so subscribing to
# them raises instead of silently never firing.
NIIVUE_EVENT_NAMES: frozenset[str] = frozenset({
    "angleCompleted",
    "annotationAdded",
    "annotationChanged",
    "annotationRemoved",
    "azimuthElevationChange",
    "change",
    "clickToSegment",
    "clipPlaneChange",
    "colormapAdded",
    "documentLoaded",
    "dragRelease",
    "drawingChanged",
    "drawingEnabled",
    "frameChange",
    "graphRangeChange",
    "locationChange",
    "measurementCompleted",
    "meshLoaded",
    "meshRemoved",
    "meshUpdated",
    "penValueChanged",
    "perfFrame",
    "pointerUp",
    "signalLoaded",
    "signalLocationChange",
    "signalRemoved",
    "sliceTypeChange",
    "volumeLoaded",
    "volumeOrderChanged",
    "volumeRemoved",
    "volumeUpdated",
})


class _GeneratedNiiVue(anywidget.AnyWidget):
    """Auto-generated reactive properties and command methods.

    Mirrors NiiVue @ niivue 1.0.0-rc.12.

    Reactive properties are kept in sync with the JS view via
    anywidget. Methods send command messages over the same
    channel. Void-returning methods are fire-and-forget;
    value-returning methods use request/response correlation
    and should return small JSON-serializable payloads.
    """

    # Synthetic inbox for Python-to-JS commands. Python may queue
    # commands immediately after display(nv), before the browser view
    # has loaded this widget module and registered msg:custom handlers.
    # Storing commands as synced state makes that cold-start path
    # durable; JS processes any unhandled seq values after initialize.
    _msg_inbox = traitlets.List([]).tag(sync=True)

    # Highest seq from `_msg_inbox` that JS has fully drained. JS sets
    # this after each inbox-processing pass; Python observes it and
    # prunes acknowledged items so a session's worth of buffer payloads
    # does not pin base64 strings in trait state forever.
    _msg_inbox_ack = traitlets.Int(0).tag(sync=True)

    # Synthetic outbox for JS-to-Python messages. anywidget 0.9.x +
    # ipywidgets 8.x do not reliably route `model.send()` from JS
    # through Python's `on_msg` callbacks in our setup; the
    # message succeeds JS-side but vanishes before reaching the
    # Python widget. As a workaround, JS writes outbound
    # messages here (a Dict trait with a monotonic seq), Python
    # observes `change:_msg_outbox`, and `widget.NiiVue` routes
    # the body through `_dispatch_message`. State-update is the
    # same channel the seed-step uses, which is verifiably
    # reliable end-to-end.
    _msg_outbox = traitlets.Dict({}).tag(sync=True)

    # Reactive properties (read+write, synced)
    annotation_active_group = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    annotation_active_label = traitlets.Float(None, allow_none=True).tag(sync=True)
    annotation_brush_radius = traitlets.Float(None, allow_none=True).tag(sync=True)
    annotation_is_enabled = traitlets.Bool(None, allow_none=True).tag(sync=True)
    """Enable vector annotation editing. Mutually exclusive with
{@link drawIsEnabled} in practice: with both on, raster drawing intercepts
the pointer and vector annotation editing is inert (the first such
interaction warns). Turn one off before turning the other on. Does not
affect whether annotations *render* — they always do."""
    annotation_is_erasing = traitlets.Bool(None, allow_none=True).tag(sync=True)
    annotation_is_visible_in_3d = traitlets.Bool(None, allow_none=True).tag(sync=True)
    annotation_merges_overlaps = traitlets.Bool(None, allow_none=True).tag(sync=True)
    annotation_tool = traitlets.Enum(["freehand", "ellipse", "rectangle", "line", "arrow", "measureEllipse", "measureRect", "measureLine", "circle", "measureCircle", "spline", "measureSpline", "livewire", "measureLivewire", "bidirectional", "measureBidirectional"], None, allow_none=True).tag(sync=True)
    azimuth = traitlets.Float(None, allow_none=True).tag(sync=True)
    background_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=4, maxlen=4, allow_none=True).tag(sync=True)
    clip_plane_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    clip_plane_overlay = traitlets.Bool(None, allow_none=True).tag(sync=True)
    crosshair_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    crosshair_gap = traitlets.Float(None, allow_none=True).tag(sync=True)
    crosshair_pos = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=3, maxlen=3, allow_none=True).tag(sync=True)
    crosshair_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    device_pixel_ratio = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_click_to_segment_is_2d = traitlets.Bool(None, allow_none=True).tag(sync=True)
    draw_click_to_segment_tolerance = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_colormap = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    draw_is_click_to_segment = traitlets.Bool(None, allow_none=True).tag(sync=True)
    draw_is_enabled = traitlets.Bool(None, allow_none=True).tag(sync=True)
    """Enable the raster drawing tools (pen/eraser/fill/magic wand). Mutually
exclusive with {@link annotationIsEnabled} in practice: with both on, raster
drawing intercepts the pointer and vector annotation editing is inert (the
first such interaction warns). Turn one off before turning the other on.
`false` stops editing but keeps the drawing visible; see `closeDrawing()`."""
    draw_is_fill_overwriting = traitlets.Bool(None, allow_none=True).tag(sync=True)
    draw_opacity = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_pen_size = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_pen_value = traitlets.Float(None, allow_none=True).tag(sync=True)
    draw_rim_opacity = traitlets.Float(None, allow_none=True).tag(sync=True)
    elevation = traitlets.Float(None, allow_none=True).tag(sync=True)
    font_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    font_min_size = traitlets.Float(None, allow_none=True).tag(sync=True)
    font_scale = traitlets.Float(None, allow_none=True).tag(sync=True)
    force_device_pixel_ratio = traitlets.Float(None, allow_none=True).tag(sync=True)
    gamma = traitlets.Float(None, allow_none=True).tag(sync=True)
    graph_auto_reset_view = traitlets.Bool(None, allow_none=True).tag(sync=True)
    graph_is_range_cal_min_max = traitlets.Bool(None, allow_none=True).tag(sync=True)
    graph_line_alpha = traitlets.Float(None, allow_none=True).tag(sync=True)
    graph_line_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    graph_normalize_values = traitlets.Bool(None, allow_none=True).tag(sync=True)
    graph_show_volume_timecourse = traitlets.Bool(None, allow_none=True).tag(sync=True)
    hero_fraction = traitlets.Float(None, allow_none=True).tag(sync=True)
    hero_slice_type = traitlets.Float(None, allow_none=True).tag(sync=True)
    is_3d_crosshair_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_annotation_drawn = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_clip_plane_cutaway = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_colorbar_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_cross_lines_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_drag_drop_enabled = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_dragging = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_equal_size = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_graph_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_legend_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_measurement_drawn = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_measure_units_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_mosaic_centered = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_orientation_text_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_orient_cube_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_position_in_mm = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_radiological = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_ruler_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_snap_to_voxel_centers = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_thumbnail_visible = traitlets.Bool(None, allow_none=True).tag(sync=True)
    is_yoked_3d_to_2d_zoom = traitlets.Bool(None, allow_none=True).tag(sync=True)
    measure_line_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    measure_text_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    mesh_thickness_on_2d = traitlets.Float(None, allow_none=True).tag(sync=True)
    mesh_x_ray = traitlets.Float(None, allow_none=True).tag(sync=True)
    mosaic_string = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    multiplanar_type = traitlets.Float(None, allow_none=True).tag(sync=True)
    pan_2_dxyzmm = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=4, maxlen=4, allow_none=True).tag(sync=True)
    placeholder_text = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    primary_drag_mode = traitlets.Float(None, allow_none=True).tag(sync=True)
    render_pan = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=2, maxlen=2, allow_none=True).tag(sync=True)
    render_pivot_mm = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=3, maxlen=3, allow_none=True).tag(sync=True)
    ruler_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    scale_multiplier = traitlets.Float(None, allow_none=True).tag(sync=True)
    secondary_drag_mode = traitlets.Float(None, allow_none=True).tag(sync=True)
    selection_box_color = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True)
    show_render = traitlets.Float(None, allow_none=True).tag(sync=True)
    slice_type = traitlets.Float(None, allow_none=True).tag(sync=True)
    slide_tool = traitlets.Enum(["pen", "eraser", "bucket", "filled", "wand", "vector"], None, allow_none=True).tag(sync=True)
    slide_wand_tolerance = traitlets.Float(None, allow_none=True).tag(sync=True)
    thumbnail_url = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    tile_margin = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_alpha_shader = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_illumination = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_is_alpha_clip_dark = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_background_masking = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_colormap_alpha_on_2d = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_nearest_interpolation = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_is_v1_slice_shader = traitlets.Bool(None, allow_none=True).tag(sync=True)
    volume_matcap = traitlets.Unicode(None, allow_none=True).tag(sync=True)
    volume_outline_width = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_paqd_uniforms = traitlets.List(trait=traitlets.Float(None, allow_none=True), default_value=None, minlen=4, maxlen=4, allow_none=True).tag(sync=True)
    volume_render_mode = traitlets.Float(None, allow_none=True).tag(sync=True)
    volume_transmittance_cutoff = traitlets.Float(None, allow_none=True).tag(sync=True)

    # Read-only properties (synced from JS to Python)
    backend = traitlets.Enum(["webgpu", "webgl2"], None, allow_none=True).tag(sync=True, o2py_readonly=True)
    colormaps = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    drawing_colormaps = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    is_anti_alias = traitlets.Bool(None, allow_none=True).tag(sync=True, o2py_readonly=True)
    is_destroyed = traitlets.Bool(None, allow_none=True).tag(sync=True, o2py_readonly=True)
    """True once {@link destroy} has run. Lets external holders (e.g. an
NVChunkedVolume handle listening for `viewDestroyed`) distinguish a real
controller teardown from a transient view recreation (backend switch /
init fallback), which also emits `viewDestroyed` but leaves the controller
and its volumes alive."""
    mesh_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    mesh_shaders = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    mesh_write_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    selected_annotation = traitlets.Unicode(None, allow_none=True).tag(sync=True, o2py_readonly=True)
    volume_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    volume_transforms = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)
    """Get list of available volume transform names."""
    volume_write_extensions = traitlets.List(trait=traitlets.Unicode(None, allow_none=True), default_value=None, allow_none=True).tag(sync=True, o2py_readonly=True)

    # Command methods
    def add_annotation(self, annotation: Any) -> None:
        self.send({"cmd": "addAnnotation", "args": _make_args(annotation)})

    async def add_colormap(self, name: Any, cmap: Any) -> Any:
        """Register a colormap by name so it becomes available to `setVolume({ colormap: name })`, `nv1.colormaps`, colorbars, mesh layers, and so on.

        Use this to add user-defined LUTs at runtime.
        Re-registering an existing name replaces the entry. Does not trigger a
        redraw — the colormap is inert until a volume references it.

        Label colormaps (for atlas volumes with per-index labels) have their
        own registration path: `setColormapLabel()` / `setColormapLabelFromUrl()`.

        Parameters
        ----------
        name : string
        cmap : Pick<ColorMap, \"R\" | \"G\" | \"B\"> & Partial<Pick<ColorMap, \"A\" | \"I\" | \"labels\">>

        Returns
        -------
        string
            The canonical name under which the colormap was stored
            (first letter upper-cased), which is the form visible in `nv1.colormaps`
            and the `colormapAdded` event detail.
        """
        return await self._request("addColormap", _make_args(name, cmap))

    def add_colormap_from_url(self, url: Any, name: Any = _UNSET) -> None:
        """Fetch a colormap JSON (`{ R, G, B, A?, I? }`) from a URL or `File` and register it under `name`.

        When `name` is omitted, it is derived from
        the source filename; callers passing an un-nameable source (e.g.
        `?query-only`) should supply `name` explicitly — an empty derived
        name throws.

        Parameters
        ----------
        url : string | File
        name : string | undefined
        """
        self.send({"cmd": "addColormapFromUrl", "args": _make_args(url, name)})

    def add_image(self, path_or_file: Any, options: Any = _UNSET) -> None:
        self.send({"cmd": "addImage", "args": _make_args(path_or_file, options)})

    def add_mesh(self, mesh: Any) -> None:
        self.send({"cmd": "addMesh", "args": _make_args(mesh)})

    def add_mesh_layer(self, mesh_index: Any, layer_opts: Any) -> None:
        """Add a scalar overlay layer to a mesh.

        Parameters
        ----------
        mesh_index : number
        layer_opts : MeshLayerFromUrlOptions
        """
        self.send({"cmd": "addMeshLayer", "args": _make_args(mesh_index, layer_opts)})

    def add_mrsi_signal(self, volume_id: Any, opts: Any = _UNSET) -> None:
        """Add a spectroscopy signal whose spectrum is read live from the crosshair voxel of a complex MRSI volume (loaded on the volume path; carries `complexFID` + `mrsMeta`).

        The graph re-derives the voxel's spectrum on
        every crosshair move — the core enabler for MRSI navigation. FSL-MRS
        `halveFirstPoint` is on by default; pass `display` to override or to set a
        ppm window/component. Throws if `volumeId` is not a loaded MRSI volume.

        Parameters
        ----------
        volume_id : string
        opts : { name?: string | undefined; display?: Partial<NVSignalDisplay> | undefined; annotations?: SignalAnnotation[] | undefined; }
        """
        self.send({"cmd": "addMrsiSignal", "args": _make_args(volume_id, opts)})

    def add_signal(self, signal: Any) -> None:
        """Add a pre-built signal or load one from a URL/File.

        Parameters
        ----------
        signal : NVSignal | SignalFromUrlOptions
        """
        self.send({"cmd": "addSignal", "args": _make_args(signal)})

    def add_volume(self, volume: Any) -> None:
        self.send({"cmd": "addVolume", "args": _make_args(volume)})

    def annotation_redo(self) -> None:
        self.send({"cmd": "annotationRedo", "args": []})

    async def annotations_to_svg(self, slice_type: Any = _UNSET, slice_position: Any = _UNSET) -> Any:
        """Serialize the vector annotations to a standalone SVG string (`<path>` per polygon, one `<g>` panel per slice plane).

        `sliceType` defaults to the current
        single-slice view; in render/multiplanar/none (no single plane on screen)
        every plane is exported, each panel laid out left-to-right, so shapes drawn
        directly on the 3D blocks all export rather than only those sharing the first
        annotation's plane.

        Path coordinates are panel-local at mm scale; each `<g>` carries
        `data-origin-mm=\"minX maxY\"` to convert back (`mmX = xLocal + minX`,
        `mmY = maxY - yLocal`).

        `slicePosition` restricts the export to one slice and requires a single plane
        — a depth is measured along that plane's own axis, so it cannot select across
        planes. Passing it with no single plane (and no explicit `sliceType`) warns
        and is ignored. Returns null when there are no annotations.

        Parameters
        ----------
        slice_type : number | undefined
        slice_position : number | undefined

        Returns
        -------
        string | null
        """
        return await self._request("annotationsToSVG", _make_args(slice_type, slice_position))

    def annotation_undo(self) -> None:
        self.send({"cmd": "annotationUndo", "args": []})

    def apply_volume_transform(self, volume_index: Any, transform: Any) -> None:
        self.send({"cmd": "applyVolumeTransform", "args": _make_args(volume_index, transform)})

    def attach_to(self, id: Any, is_anti_alias: Any = _UNSET) -> None:
        self.send({"cmd": "attachTo", "args": _make_args(id, is_anti_alias)})

    def broadcast_to(self, targets: Any = _UNSET, opts: Any = _UNSET) -> None:
        """Sync the scene controls (orientation, crosshair location, etc.) from one NiiVue instance to others.

        Parameters
        ----------
        targets : default | default[] | undefined
            the other NiiVue instance(s) to broadcast to, or omit to clear sync
        opts : SyncOpts
            which properties to sync (default: { '2d': true, '3d': true })
        """
        self.send({"cmd": "broadcastTo", "args": _make_args(targets, opts)})

    async def center_render_on_mm(self, mm: Any) -> Any:
        """Pan the 3D render so a given world-mm point sits at the centre of the render tile, by adjusting `renderPan` (a clip-space translation; no change to the camera, rotation, or zoom).

        Useful to keep a zoomed/focused region framed.
        Returns false (no-op) if the render tile hasn't been drawn yet. Because the
        cached MVP already includes the current renderPan, this converges in one
        call: newPan = currentPan - ndc(point).

        Parameters
        ----------
        mm : [number, number, number]

        Returns
        -------
        boolean
        """
        return await self._request("centerRenderOnMM", _make_args(mm))

    async def chunk_stream_stats(self) -> Any:
        """Streaming stats across all chunked volumes (base + independent overlay) on the active backend: `{ resident, pending, inFlight, total }` brick counts.

        Returns null before a view is attached. Useful for HUD / debug overlays:
        `resident < total` with `pending > 0` for many frames indicates the working
        set exceeds the residency budget (thrashing).

        Returns
        -------
        { resident: number; pending: number; inFlight: number; total: number; } | null
        """
        return await self._request("chunkStreamStats", [])

    def clear_angles(self) -> None:
        """Clear completed angles only, leaving distance measurements in place.
        """
        self.send({"cmd": "clearAngles", "args": []})

    def clear_annotations(self) -> None:
        self.send({"cmd": "clearAnnotations", "args": []})

    def clear_bounds(self) -> None:
        """Give this instance the whole canvas again, undoing {@link setBounds}.

        Equivalent to `setBounds([0, 0, 1, 1])`.
        """
        self.send({"cmd": "clearBounds", "args": []})

    def clear_custom_layout(self) -> None:
        """Clear any custom layout and revert to built-in layout modes.
        """
        self.send({"cmd": "clearCustomLayout", "args": []})

    def clear_distance_measurements(self) -> None:
        """Clear completed distance measurements only, leaving angles in place.
        """
        self.send({"cmd": "clearDistanceMeasurements", "args": []})

    def clear_measurements(self) -> None:
        """Clear both completed distance measurements and completed angles.
        """
        self.send({"cmd": "clearMeasurements", "args": []})

    def clear_slide_drawing(self) -> None:
        """Clear all slide annotation pixels.
        """
        self.send({"cmd": "clearSlideDrawing", "args": []})

    def clear_slide_plane(self) -> None:
        """Remove a slide plane registered with {@link setSlidePlane}.
        """
        self.send({"cmd": "clearSlidePlane", "args": []})

    def close_drawing(self) -> None:
        self.send({"cmd": "closeDrawing", "args": []})

    def create_empty_drawing(self) -> None:
        self.send({"cmd": "createEmptyDrawing", "args": []})

    def create_on_location_change(self, ax_cor_sag: Any = _UNSET) -> None:
        self.send({"cmd": "createOnLocationChange", "args": _make_args(ax_cor_sag)})

    def create_slide_drawing(self, opts: Any = _UNSET) -> None:
        """Create a drawing surface in *slide* space for the registered slide plane.

        The annotation is a label raster covering the whole slide (sized to the
        slide aspect, long edge capped at `maxRaster`, default 4096) and is painted
        with the existing pen tools (slideDrawAt / slideDrawUndo reuse drawPoint,
        drawLine and the RLE undo stack), so it stays in slide coordinates and is
        compatible with the volume drawing functions. Requires {@link setSlidePlane}.

        Parameters
        ----------
        opts : { maxRaster?: number | undefined; } | undefined
        """
        self.send({"cmd": "createSlideDrawing", "args": _make_args(opts)})

    def destroy(self) -> None:
        self.send({"cmd": "destroy", "args": []})

    async def drawing_to_svg(self, slice_type: Any = _UNSET, slice_index: Any = _UNSET) -> Any:
        """Serialize one slice of the voxel drawing to a standalone SVG string (run-length `<rect>`s per label color, sized in voxels).

        `sliceType` selects
        the plane (AXIAL/CORONAL/SAGITTAL); it defaults to the current single-slice
        view, or AXIAL for render/multiplanar/none. `sliceIndex` defaults to the
        crosshair voxel on that axis. Returns null when no drawing is open.

        Parameters
        ----------
        slice_type : number | undefined
        slice_index : number | undefined

        Returns
        -------
        string | null
        """
        return await self._request("drawingToSVG", _make_args(slice_type, slice_index))

    def draw_scene(self, needs_sync: Any = _UNSET) -> None:
        self.send({"cmd": "drawScene", "args": _make_args(needs_sync)})

    def draw_undo(self) -> None:
        self.send({"cmd": "drawUndo", "args": []})

    def enforce_backend_availability(self) -> None:
        self.send({"cmd": "enforceBackendAvailability", "args": []})

    def ensure_graph_cursor_visible(self) -> None:
        """After the marker moves on its own (e.g.

        the wheel stepped the 4D frame), pan
        the zoom window so the marker stays visible. No-op at full extent or when it
        is already in view.
        """
        self.send({"cmd": "ensureGraphCursorVisible", "args": []})

    async def get_annotations_json(self) -> Any:
        return await self._request("getAnnotationsJSON", [])

    async def get_clip_plane_depth_azi_elev(self, clip_plane_index: Any = _UNSET) -> Any:
        return await self._request("getClipPlaneDepthAziElev", _make_args(clip_plane_index))

    async def get_crosshair_pos(self) -> Any:
        return await self._request("getCrosshairPos", [])

    async def get_descriptives(self, options: Any = _UNSET) -> Any:
        """Region-of-interest statistics for a loaded volume.

        Values are calibrated (`scl_slope`/`scl_inter` applied) and non-finite
        voxels are excluded. Every mask must sit on the same RAS grid as the
        target volume — overlays are resliced to the background grid, so masks
        drawn from the loaded volume list satisfy that by construction, but a mask
        on a different grid returns `null` rather than silently wrong numbers.

        Parameters
        ----------
        options : { volumeIndex?: number | undefined; masks?: number[] | undefined; isDrawingMask?: boolean | undefined; drawPenValues?: number[] | undefined; }

        Returns
        -------
        DescriptiveStats | null
            the statistics, or `null` when the volume has no data or a mask
            does not match the target grid
        """
        return await self._request("getDescriptives", _make_args(options))

    async def get_frame_4d(self, id: Any) -> Any:
        """Get the current 4D frame index for a volume.

        Parameters
        ----------
        id : string
            Volume ID (typically the URL or name)

        Returns
        -------
        number
            Current frame index (0-based), or 0 if volume not found
        """
        return await self._request("getFrame4D", _make_args(id))

    async def get_graph_range(self) -> Any:
        """The signal graph's current visible x-range (the synchronous counterpart to the `graphRangeChange` event): `{ min, max, full, axisLabel, isWindowed }`, or null when no signal graph is shown.

        Use `full` to drive a \"reset to full
        extent\" control (e.g. jump range sliders to the data limits).

        Returns
        -------
        GraphRangeChangeDetail | null
        """
        return await self._request("getGraphRange", [])

    async def get_mesh_shader(self, mesh_index: Any) -> Any:
        return await self._request("getMeshShader", _make_args(mesh_index))

    async def get_tract_groups(self, mesh_index: Any) -> Any:
        """Get the group names for a tract mesh.

        Returns an empty array if the mesh is not a tract or has no groups.

        Parameters
        ----------
        mesh_index : number

        Returns
        -------
        string[]
        """
        return await self._request("getTractGroups", _make_args(mesh_index))

    async def get_viewport(self) -> Any:
        """Read the canvas-level viewport (virtual camera) shared with sibling instances.

        The viewport applies a pan + zoom over the entire canvas before each instance's
        `bounds` are projected to pixels. Identity is `{pan: [0, 0], zoom: 1}`.

        Returns
        -------
        CanvasViewport
        """
        return await self._request("getViewport", [])

    async def get_volume_affine(self, volume_index: Any) -> Any:
        return await self._request("getVolumeAffine", _make_args(volume_index))

    async def get_volume_transform_info(self, name: Any) -> Any:
        """Get metadata for a specific volume transform (options, description, resultDefaults).

        Parameters
        ----------
        name : string

        Returns
        -------
        TransformInfo | undefined
        """
        return await self._request("getVolumeTransformInfo", _make_args(name))

    def graph_pan(self, frac: Any) -> None:
        """Pan the signal graph's x-axis view window by `frac` of its width (negative pans toward earlier x / left).

        No-op when the full extent is shown.

        Parameters
        ----------
        frac : number
        """
        self.send({"cmd": "graphPan", "args": _make_args(frac)})

    def graph_reset_view(self) -> None:
        """Reset the signal graph's zoom/pan to the full x-extent (clears the view window).

        The one-click way back from a deep zoom; also bound to a
        double-click on the graph. No-op when the full extent is already shown.
        """
        self.send({"cmd": "graphResetView", "args": []})

    def graph_zoom(self, factor: Any = _UNSET) -> None:
        """Zoom the signal graph's x-axis view window: `factor` > 1 zooms in, < 1 zooms out, centred on the graph cursor when one is set (else the window centre).

        Zooming out past the full extent restores the full view. No-op unless a
        (dense) signal graph is shown.

        Parameters
        ----------
        factor : number
        """
        self.send({"cmd": "graphZoom", "args": _make_args(factor)})

    async def has_colormap(self, name: Any) -> Any:
        """Case-insensitive existence check for a registered colormap.

        Accepts
        whatever casing the caller has on hand (e.g. a lowercased `<select>`
        value) and compares against the canonical stored name. Prefer this
        over `nv1.colormaps.includes(...)` — it handles the first-letter
        canonicalization that `addColormap` and the filesystem auto-loader
        apply internally.

        Parameters
        ----------
        name : string

        Returns
        -------
        boolean
        """
        return await self._request("hasColormap", _make_args(name))

    def load_annotations_json(self, json: Any) -> None:
        self.send({"cmd": "loadAnnotationsJSON", "args": _make_args(json)})

    async def load_chunked_volume(self, source: Any, options: Any = _UNSET) -> Any:
        """Load a multi-resolution (pyramid) volume from a pluggable {@link ChunkedVolumeSource} and render it with crosshair-focused level of detail: the finest bricks stay around the crosshair while distant regions render coarser, all under a brick/VRAM budget, so a very large finest level (e.g.

        a 20+ GB whole-slide/OME-Zarr volume) is renderable without ever
        making it fully resident. Returns an {@link NVChunkedVolume} handle
        (`setFocus` / `setMaxDetail` / `setBudget` / `dispose`); with the default
        `focus: 'crosshair'` it follows the crosshair automatically.

        ADDITIVE: the streamed volume is ADDED to the scene (via `addVolume`), not
        swapped for the current volumes. To reload/replace a streamed volume, the
        caller removes the previous one first.

        Parameters
        ----------
        source : ChunkedVolumeSource
        options : ChunkedVolumeOptions | undefined

        Returns
        -------
        Promise<NVChunkedVolume>
        """
        return await self._request("loadChunkedVolume", _make_args(source, options))

    def load_deferred_4d_volumes(self, id: Any) -> None:
        """Load all remaining frames for a 4D volume that was opened with limitFrames4D.

        Re-fetches the complete file and replaces the truncated image data.

        Parameters
        ----------
        id : string
            Volume ID (typically the URL or name)
        """
        self.send({"cmd": "loadDeferred4DVolumes", "args": _make_args(id)})

    def load_document(self, source: Any, options: Any = _UNSET) -> None:
        self.send({"cmd": "loadDocument", "args": _make_args(source, options)})

    async def load_drawing(self, source: Any) -> Any:
        return await self._request("loadDrawing", _make_args(source))

    def load_image(self, path_or_file: Any, options: Any = _UNSET) -> None:
        self.send({"cmd": "loadImage", "args": _make_args(path_or_file, options)})

    async def load_img_v1(self, volume_index: Any, is_flip_x: Any = _UNSET, is_flip_y: Any = _UNSET, is_flip_z: Any = _UNSET) -> Any:
        """Convert a float32 3-frame volume to V1 (eigenvector) RGBA representation.

        For formats like AFNI that lack NIfTI intent codes, this provides explicit
        conversion of vector field data (dim4=3, float32) to sign-encoded RGBA.

        Parameters
        ----------
        volume_index : number
            Index of the volume to convert
        is_flip_x : boolean
            Flip X component (default: false)
        is_flip_y : boolean
            Flip Y component (default: false)
        is_flip_z : boolean
            Flip Z component (default: false)

        Returns
        -------
        Promise<boolean>
        """
        return await self._request("loadImgV1", _make_args(volume_index, is_flip_x, is_flip_y, is_flip_z))

    def load_matcap(self, matcap_name: Any) -> None:
        self.send({"cmd": "loadMatcap", "args": _make_args(matcap_name)})

    def load_meshes(self, meshes: Any) -> None:
        self.send({"cmd": "loadMeshes", "args": _make_args(meshes)})

    def load_signals(self, signals: Any) -> None:
        """Load one or more signals (physio TSV or NIfTI/NIfTI-MRS).

        Parameters
        ----------
        signals : SignalFromUrlOptions | SignalFromUrlOptions[]
        """
        self.send({"cmd": "loadSignals", "args": _make_args(signals)})

    def load_volumes(self, volumes: Any) -> None:
        self.send({"cmd": "loadVolumes", "args": _make_args(volumes)})

    def mark_draw_dirty(self, x: Any, y: Any, z: Any, radius: Any = _UNSET) -> None:
        """Expand the pending pen-stroke dirty box by a voxel and its pen radius, so the next drawing flush re-uploads only the chunks that region touches.

        Call
        this right before `refreshDrawing()` at each pen-stroke site; whole-bitmap
        changes (undo, clear, recolour) skip it and fall back to a full upload.

        Parameters
        ----------
        x : number
        y : number
        z : number
        radius : number
        """
        self.send({"cmd": "markDrawDirty", "args": _make_args(x, y, z, radius)})

    async def mm2render_ndc(self, mm: Any) -> Any:
        """Project a world-mm point to the 3D render tile's NDC ([-1,1], y up), using the MVP the renderer cached on its last draw (so it reflects the current camera, zoom, and renderPan exactly).

        Returns null if no render tile has been
        drawn yet or the point is at/behind the camera.

        Parameters
        ----------
        mm : [number, number, number]

        Returns
        -------
        [number, number] | null
        """
        return await self._request("mm2renderNDC", _make_args(mm))

    def move_crosshair_in_vox(self, di: Any, dj: Any, dk: Any) -> None:
        self.send({"cmd": "moveCrosshairInVox", "args": _make_args(di, dj, dk)})

    def move_volume_down(self, volume_index: Any) -> None:
        """Move a volume down one index position in the stack of loaded volumes (toward the background).

        Parameters
        ----------
        volume_index : number
            Index of the volume to move
        """
        self.send({"cmd": "moveVolumeDown", "args": _make_args(volume_index)})

    def move_volume_to_bottom(self, volume_index: Any) -> None:
        """Move a volume to the bottom position in the stack of loaded volumes (index 0, background).

        Parameters
        ----------
        volume_index : number
            Index of the volume to move
        """
        self.send({"cmd": "moveVolumeToBottom", "args": _make_args(volume_index)})

    def move_volume_to_top(self, volume_index: Any) -> None:
        """Move a volume to the top position in the stack of loaded volumes (last index, top layer).

        Parameters
        ----------
        volume_index : number
            Index of the volume to move
        """
        self.send({"cmd": "moveVolumeToTop", "args": _make_args(volume_index)})

    def move_volume_up(self, volume_index: Any) -> None:
        """Move a volume up one index position in the stack of loaded volumes (toward the top layer).

        Parameters
        ----------
        volume_index : number
            Index of the volume to move
        """
        self.send({"cmd": "moveVolumeUp", "args": _make_args(volume_index)})

    def rebake_chunked_overlays(self) -> None:
        """Re-bake the streamed/chunked overlays in place: drop their resident bricks so the next frame re-requests and re-bakes only the blocks in the current view frustum, leaving the base volume resident.

        Use after changing a streamed
        overlay's `opacity` (or any `chunkSource` whose output changed) to apply it
        without the cost of a full `loadVolumes` reload. No-op before a view attaches.
        """
        self.send({"cmd": "rebakeChunkedOverlays", "args": []})

    def recalculate_cal_min_max(self, volume_index: Any, frame: Any = _UNSET) -> None:
        """Recalculate robust cal_min/cal_max for a specific 4D frame (or the current frame).

        Updates the volume's calibration range and triggers a GPU update.

        Parameters
        ----------
        volume_index : number
        frame : number | undefined
        """
        self.send({"cmd": "recalculateCalMinMax", "args": _make_args(volume_index, frame)})

    def refresh_drawing(self) -> None:
        """Mark the drawing texture as dirty and schedule a redraw.

        The expensive bitmap→RGBA conversion and GPU upload are deferred to
        the next animation frame, so rapid pointermove events only pay the
        cost once per frame.
        """
        self.send({"cmd": "refreshDrawing", "args": []})

    def refresh_signal_location(self) -> None:
        """Re-emit the signal readout at the current marker (the associated volume's frame time, else the last clicked cursor).

        Called on crosshair/frame changes
        so the status bar reflects the current voxel value without a graph click.
        """
        self.send({"cmd": "refreshSignalLocation", "args": []})

    def refresh_slide_annotation(self) -> None:
        """Rebuild the slide annotation overlay (raster + vector) and redraw.

        Call
        after mutating `slideVector`.
        """
        self.send({"cmd": "refreshSlideAnnotation", "args": []})

    async def reinitialize_view(self, options: Any = _UNSET) -> Any:
        return await self._request("reinitializeView", _make_args(options))

    def remove_all_meshes(self) -> None:
        self.send({"cmd": "removeAllMeshes", "args": []})

    def remove_all_signals(self) -> None:
        self.send({"cmd": "removeAllSignals", "args": []})

    def remove_all_volumes(self) -> None:
        self.send({"cmd": "removeAllVolumes", "args": []})

    def remove_annotation(self, id: Any) -> None:
        self.send({"cmd": "removeAnnotation", "args": _make_args(id)})

    def remove_mesh(self, mesh_index: Any) -> None:
        self.send({"cmd": "removeMesh", "args": _make_args(mesh_index)})

    def remove_mesh_layer(self, mesh_index: Any, layer_index: Any) -> None:
        """Remove a scalar overlay layer from a mesh.

        Parameters
        ----------
        mesh_index : number
        layer_index : number
        """
        self.send({"cmd": "removeMeshLayer", "args": _make_args(mesh_index, layer_index)})

    def remove_signal(self, index: Any) -> None:
        self.send({"cmd": "removeSignal", "args": _make_args(index)})

    def remove_volume(self, volume_index: Any) -> None:
        """Remove a single volume by index, emitting `volumeRemoved`.

        Parameters
        ----------
        volume_index : number
            Index of the volume to remove
        """
        self.send({"cmd": "removeVolume", "args": _make_args(volume_index)})

    def reset_volume_affine(self, volume_index: Any) -> None:
        self.send({"cmd": "resetVolumeAffine", "args": _make_args(volume_index)})

    def resize(self) -> None:
        self.send({"cmd": "resize", "args": []})

    def restore_slide_plane_view(self) -> None:
        """Re-push the registered slide plane (and its annotation) to a freshly (re)created view — called from the view-lifecycle recreate paths so a backend switch / reinitialize doesn't drop the slide.

        Internal.
        """
        self.send({"cmd": "restoreSlidePlaneView", "args": []})

    async def save_bitmap(self, filename: Any = _UNSET, quality: Any = _UNSET) -> Any:
        return await self._request("saveBitmap", _make_args(filename, quality))

    def save_document(self, filename: Any = _UNSET, options: Any = _UNSET) -> None:
        self.send({"cmd": "saveDocument", "args": _make_args(filename, options)})

    async def save_drawing(self, filename: Any = _UNSET) -> Any:
        return await self._request("saveDrawing", _make_args(filename))

    def save_mesh(self, mesh_index: Any, filename: Any = _UNSET, options: Any = _UNSET) -> None:
        self.send({"cmd": "saveMesh", "args": _make_args(mesh_index, filename, options)})

    async def save_volume(self, options: Any = _UNSET) -> Any:
        """Save voxel-based image to disk.

        Parameters
        ----------
        options : SaveVolumeOptions
            configuration object with the following fields:
            - `filename`: name of the NIfTI image to create. If empty, returns data only.
            - `isSaveDrawing`: whether to save the drawing layer or the background image
            - `volumeByIndex`: which image layer to save (0 for background)

        Returns
        -------
        Promise<boolean | Uint8Array>
            `true` if successful when writing to disk, or a `Uint8Array` if exported as binary data
        """
        return await self._request("saveVolume", _make_args(options))

    def select_annotation(self, id: Any) -> None:
        self.send({"cmd": "selectAnnotation", "args": _make_args(id)})

    async def serialize_document(self, options: Any = _UNSET) -> Any:
        """Return the current scene serialized as an NVD document (Uint8Array).

        `options.settings` overrides the instance `settingsSavePolicy`;
        `options.linkData` saves a small \"linked\" document that references volumes by
        URL instead of embedding their bytes; `options.format` is `'cbor'` (default,
        binary) or `'json'` (portable text). `loadDocument` accepts either encoding.

        Parameters
        ----------
        options : SerializeOptions | undefined

        Returns
        -------
        Uint8Array
        """
        return await self._request("serializeDocument", _make_args(options))

    def set_annotation_text(self, id: Any, text: Any) -> None:
        """Set (or clear, with an empty string) the free-text label on an annotation by id.

        The text shows above the annotation's stats via the overlay seam.

        Parameters
        ----------
        id : string
        text : string
        """
        self.send({"cmd": "setAnnotationText", "args": _make_args(id, text)})

    def set_atlas_outline(self, outline: Any, volume_index: Any = _UNSET) -> None:
        """Draw label/atlas volumes as region outlines rather than filled regions.

        `outline` is the neighbour probe distance in the atlas's own voxels: 0 (the
        default) fills every region, 1 keeps a one-voxel border, larger values give
        a thicker border. Only the interior is dropped, so the parcellation stays
        readable over the anatomy underneath. Non-label volumes ignore it.

        Applies to every loaded label volume when `volumeIndex` is omitted, or to
        one volume when it is given. It is a per-volume property, so
        `setVolume(i, { atlasOutline })` and the load options reach it too.

        ```js
        nv1.setAtlasOutline(1)     // outline every atlas
        nv1.setAtlasOutline(0, 1)  // fill volume 1 again
        ```

        Parameters
        ----------
        outline : number
        volume_index : number | undefined
        """
        self.send({"cmd": "setAtlasOutline", "args": _make_args(outline, volume_index)})

    def set_base_coarse_floor(self, coarse_vol: Any) -> None:
        """Set (or clear, with null) a coarse whole-volume \"floor\" for the streamed base.

        On 2D slices the floor renders behind the resident fine chunks, so a
        deep-zoom slice shows coarse detail immediately and never blanks while
        finer chunks stream in — a smooth level-of-detail transition. `coarseVol`
        is a small in-memory pyramid level (its own colormap/window); niivue stays
        level-of-detail-agnostic and the app supplies it. No-op before a view
        attaches or on a backend that has not implemented it.

        Parameters
        ----------
        coarse_vol : NVImage | null
        """
        self.send({"cmd": "setBaseCoarseFloor", "args": _make_args(coarse_vol)})

    def set_bounds(self, bounds: Any) -> None:
        """Update the drawing bounds for this Niivue instance.

        Coordinates use y=0 at bottom, y=1 at top (GL convention).

        Parameters
        ----------
        bounds : [number, number, number, number]
            [x1, y1, x2, y2] in normalized (0-1) coordinates.

            Example:
            nv.setBounds([0,0,0.5,0.5])   // bottom-left quarter
            nv.setBounds([0.5,0.5,1,1])   // top-right quarter
        """
        self.send({"cmd": "setBounds", "args": _make_args(bounds)})

    def set_clip_plane(self, depth_azimuth_elevation: Any) -> None:
        self.send({"cmd": "setClipPlane", "args": _make_args(depth_azimuth_elevation)})

    def set_clip_plane_depth_azi_elev(self, depth: Any, azimuth: Any, elevation: Any, clip_plane_index: Any = _UNSET) -> None:
        self.send({"cmd": "setClipPlaneDepthAziElev", "args": _make_args(depth, azimuth, elevation, clip_plane_index)})

    def set_clip_planes(self, depth_azi_elevs: Any) -> None:
        self.send({"cmd": "setClipPlanes", "args": _make_args(depth_azi_elevs)})

    def set_colormap_label(self, volume_index: Any, cmap: Any) -> None:
        """Set a label colormap on a volume (e.g., atlas/parcellation).

        Converts the ColorMap definition to an LUT and attaches it to the volume.
        When set, the orient shader uses nearest-neighbor label lookup instead of
        continuous colormap interpolation, and locationChange events include label names.

        Parameters
        ----------
        volume_index : number
            Index of the volume to apply the label colormap to
        cmap : string | ColorMap | null
            ColorMap definition with R,G,B arrays and optional labels/I arrays;
            a built-in colormap name (e.g. 'freesurfer', resolved via
            lookupColorMap); or null to remove the label colormap
        """
        self.send({"cmd": "setColormapLabel", "args": _make_args(volume_index, cmap)})

    def set_colormap_label_from_url(self, volume_index: Any, url: Any) -> None:
        """Fetch a label colormap JSON from a URL or File and apply it to a volume.

        The JSON should contain R, G, B arrays and optional labels/I arrays.

        Parameters
        ----------
        volume_index : number
            Index of the volume to apply the label colormap to
        url : string | File
            URL string or File object pointing to a colormap JSON
        """
        self.send({"cmd": "setColormapLabelFromUrl", "args": _make_args(volume_index, url)})

    def set_connectome_options(self, mesh_index: Any, options: Any) -> None:
        """Update connectome extrusion/display options and re-extrude.

        Parameters
        ----------
        mesh_index : number
        options : Partial<NVConnectomeOptions>
        """
        self.send({"cmd": "setConnectomeOptions", "args": _make_args(mesh_index, options)})

    def set_crosshair_pos(self, pos: Any) -> None:
        self.send({"cmd": "setCrosshairPos", "args": _make_args(pos)})

    def set_drag_mode(self, mode: Any) -> None:
        self.send({"cmd": "setDragMode", "args": _make_args(mode)})

    async def set_font(self, font: Any) -> Any:
        """Swap the active font atlas.

        The font is infrastructure-level configuration
        (GPU-owned atlas texture + metrics map), so switching requires a full view
        rebuild — use this method instead of mutating `opts.font` directly.

        Parameters
        ----------
        font : NVFontData

        Returns
        -------
        Promise<boolean>
        """
        return await self._request("setFont", _make_args(font))

    async def set_font_from_url(self, urls: Any) -> Any:
        """Fetch an MSDF font atlas (PNG + JSON metrics pair) from URLs and swap it in as the active font.

        Useful for loading fonts that are not bundled
        with the library (e.g. the community atlases at
        https://github.com/niivue/fonts). The PNG URL is stored verbatim and
        used as the GPU atlas texture source.

        On failure (metrics fetch, view rebuild, or atlas texture upload)
        the previous font is restored so the view isn't left half-initialized.
        The original error is re-thrown after recovery.

        Parameters
        ----------
        urls : { atlas: string; metrics: string; }

        Returns
        -------
        Promise<boolean>
        """
        return await self._request("setFontFromUrl", _make_args(urls))

    def set_frame_4d(self, id: Any, frame: Any) -> None:
        """Set the current 4D frame for a volume.

        Parameters
        ----------
        id : string
            Volume ID (typically the URL or name)
        frame : number
            Frame index (0-based, clamped to valid range)
        """
        self.send({"cmd": "setFrame4D", "args": _make_args(id, frame)})

    def set_global_camera(self, camera: Any) -> None:
        """Update the shared 3D camera used by `space === 'global3d'` instances.

        Supported on both WebGL2 and WebGPU backends.

        Parameters
        ----------
        camera : NVGlobalCamera
        """
        self.send({"cmd": "setGlobalCamera", "args": _make_args(camera)})

    def set_graph_range(self, range: Any) -> None:
        """Set the signal graph's visible x-range to an explicit data-unit range (order-insensitive), clamped to the full extent; `null` restores the full view.

        For a host driving the range reactively (e.g. ppm sliders that mirror
        the in-graph zoom via the `graphRangeChange` event). Pairs with
        `graphAutoResetView = false` so the window is host-owned.

        Parameters
        ----------
        range : [number, number] | null
        """
        self.send({"cmd": "setGraphRange", "args": _make_args(range)})

    def set_instances(self, instances: Any) -> None:
        """Replace the multi-instance descriptor list (canvas tiling + optional global3d volumes).

        Triggers a tile rebuild and redraw. Supported on both WebGL2 and
        WebGPU backends.

        Parameters
        ----------
        instances : NVInstance[]
        """
        self.send({"cmd": "setInstances", "args": _make_args(instances)})

    def set_mesh(self, mesh_index: Any, options: Any) -> None:
        """Update display properties of a loaded mesh.

        Accepts any subset of mesh display options (opacity, shaderType, color, etc.)
        and triggers a single GPU update.

        Parameters
        ----------
        mesh_index : number
        options : MeshUpdate
        """
        self.send({"cmd": "setMesh", "args": _make_args(mesh_index, options)})

    def set_mesh_layer_frame_4d(self, mesh_index: Any, layer_index: Any, frame: Any) -> None:
        """Set the current 4D frame for a mesh layer.

        Parameters
        ----------
        mesh_index : number
        layer_index : number
        frame : number
        """
        self.send({"cmd": "setMeshLayerFrame4D", "args": _make_args(mesh_index, layer_index, frame)})

    def set_mesh_layer_property(self, mesh_index: Any, layer_index: Any, options: Any) -> None:
        """Update properties of a mesh layer (colormap, cal_min, cal_max, opacity, etc.).

        Triggers recompositing and GPU update.

        Parameters
        ----------
        mesh_index : number
        layer_index : number
        options : Partial<NVMeshLayer>
        """
        self.send({"cmd": "setMeshLayerProperty", "args": _make_args(mesh_index, layer_index, options)})

    def set_modulation_image(self, target_id: Any, modulator_id: Any, modulate_alpha: Any = _UNSET) -> None:
        """Set a modulation image for a target volume.

        The modulator's intensity
        (windowed by its own calMin/calMax) scales the target volume's brightness
        (RGB) or opacity (alpha) per voxel.

        Works for both pre-baked RGB/RGBA volumes (V1 tensors) and plain
        colormapped SCALAR overlays — for scalar overlays the weight is sampled in
        the colormap GPU prepass through the modulator's overlay transform matrix,
        so the modulator may live on any co-registered grid.

        NOTE: `modulateAlpha` differs by target type. For SCALAR overlays it selects
        RGB (0) vs alpha (non-zero) modulation. For RGB/RGBA (V1 tensor) volumes,
        only RGB is ever scaled — alpha is preserved to keep V1 sign-polarity bits
        intact — so a non-zero `modulateAlpha` does NOT produce alpha modulation
        there (it only sets the exponent for the unused alpha path). Background-volume
        alpha modulation additionally needs `volumeIsAlphaClipDark` to show as
        transparency.

        Parameters
        ----------
        target_id : string
            ID of the volume to modulate
        modulator_id : string
            ID of the volume providing modulation (empty string to clear)
        modulate_alpha : number
            scalar overlays: 0 modulates RGB, non-zero modulates
            ALPHA with exponent `max(1, |modulateAlpha|)` (matching the original
            NiiVue). RGB/RGBA volumes always modulate RGB only.

            Re-invalidation: the scalar weight is cached by the modulator's buffer
            identity + window, so it does NOT detect an IN-PLACE edit of the modulator's
            voxel data (same buffer). After mutating a modulator in place (e.g. a
            drawing/segmentation used as a modulator), call this method again (same
            target + modulator) to force a recompute.
        """
        self.send({"cmd": "setModulationImage", "args": _make_args(target_id, modulator_id, modulate_alpha)})

    def set_signal(self, index: Any, opts: Any) -> None:
        """Update a loaded signal's display state (drives the on-demand transform).

        Parameters
        ----------
        index : number
        opts : { display?: Partial<NVSignalDisplay> | undefined; attachToId?: string | undefined; annotations?: SignalAnnotation[] | undefined; }
        """
        self.send({"cmd": "setSignal", "args": _make_args(index, opts)})

    def set_signal_cursor_fraction(self, x_frac: Any) -> None:
        """Set the signal graph cursor from a plot-relative x fraction (0 = left edge, 1 = right edge).

        Draws a faint marker line and emits `signalLocationChange`
        with the values of every series at that location (for a status-bar readout).
        In an associated volume+physio view it also scrubs the 4D volume to the
        nearest frame.

        Parameters
        ----------
        x_frac : number
        """
        self.send({"cmd": "setSignalCursorFraction", "args": _make_args(x_frac)})

    def set_slide_plane(self, slide: Any, opts: Any) -> None:
        """Register an NVSlide to render as a textured plane in the 3D render view, laid into the loaded volume's world (mm) space.

        `pixelToWorld` maps slide
        base pixels -> world mm (build one with `axialPlaneTransform` for an
        axis-aligned plane). By default the pyramid level is chosen per-frame from
        the camera distance (`resolveSlidePlaneTiles`) so the plane sharpens as you
        zoom in; pass `levelIndex` to pin a fixed level. Tiles stream via NVSlide's
        cache and the view redraws on its `change` event. Call `clearSlidePlane()`.

        Parameters
        ----------
        slide : NVSlide
        opts : { pixelToWorld: readonly number[]; levelIndex?: number | undefined; }
        """
        self.send({"cmd": "setSlidePlane", "args": _make_args(slide, opts)})

    def set_slide_plane_level(self, level_index: Any = _UNSET) -> None:
        """Pin the slide plane's pyramid level (0 = finest), or return to the camera-driven choice with undefined.

        Mutates the registered plane in
        place, so — unlike re-calling {@link setSlidePlane} — the slide drawing
        and vector annotations survive the change. No-op without a plane.

        Parameters
        ----------
        level_index : number | undefined
        """
        self.send({"cmd": "setSlidePlaneLevel", "args": _make_args(level_index)})

    def set_tract_options(self, mesh_index: Any, options: Any) -> None:
        """Update tract tessellation/display options and re-tessellate.

        Parameters
        ----------
        mesh_index : number
        options : Partial<NVTractOptions>
        """
        self.send({"cmd": "setTractOptions", "args": _make_args(mesh_index, options)})

    def set_viewport(self, viewport: Any) -> None:
        """Update the canvas-level viewport (virtual camera).

        All controllers sharing this
        canvas resize and redraw together. `pan` is in normalized canvas units (GL convention,
        y up); `zoom` is a positive scalar around the canvas centre.

        Parameters
        ----------
        viewport : CanvasViewport
            `{ pan: [x, y], zoom }`. Default identity keeps existing behavior.
        """
        self.send({"cmd": "setViewport", "args": _make_args(viewport)})

    def set_volume(self, volume_index: Any, options: Any) -> None:
        """Update display properties of a loaded volume.

        Accepts any subset of volume display options (colormap, opacity, calMin, etc.)
        and triggers a single GPU update. Note the display-window fields are the
        camelCase calMin/calMax (matching VolumeUpdate / ImageFromUrlOptions); the
        snake_case cal_min/cal_max are NIfTI header fields and are ignored here.

        Parameters
        ----------
        volume_index : number
        options : VolumeUpdate
        """
        self.send({"cmd": "setVolume", "args": _make_args(volume_index, options)})

    def set_volume_affine(self, volume_index: Any, affine: Any) -> None:
        self.send({"cmd": "setVolumeAffine", "args": _make_args(volume_index, affine)})

    async def slide_draw_at(self, css_x: Any, css_y: Any, begin: Any) -> Any:
        """Draw on the slide at a canvas CSS pixel with the active {@link slideTool}.

        `begin` starts a stroke (pen/eraser/filled), a single action (bucket/wand),
        or a new polygon (vector); subsequent calls extend it. Call slideDrawEnd on
        pointer-up. Returns false if the point misses the slide. Uses the model's
        pen value/size (eraser = penValue 0).

        Parameters
        ----------
        css_x : number
        css_y : number
        begin : boolean

        Returns
        -------
        boolean
        """
        return await self._request("slideDrawAt", _make_args(css_x, css_y, begin))

    def slide_draw_end(self) -> None:
        """End the current slide stroke; commits filled-pen / vector polygons.
        """
        self.send({"cmd": "slideDrawEnd", "args": []})

    def slide_draw_undo(self) -> None:
        """Undo the last slide action (vector tool removes the last polygon).
        """
        self.send({"cmd": "slideDrawUndo", "args": []})

    async def slide_plane_pick(self, css_x: Any, css_y: Any) -> Any:
        """Map a canvas CSS pixel to slide base-pixel coords, or null off-plane.

        Parameters
        ----------
        css_x : number
        css_y : number

        Returns
        -------
        { x: number; y: number; } | null
        """
        return await self._request("slidePlanePick", _make_args(css_x, css_y))

    def step_signal_cursor(self, direction: Any) -> None:
        """Step the signal cursor along the x-axis by one wheel tick (fraction of the visible window).

        Fallback scroll gesture for a signal graph with no spatial
        volume to scrub (when a 4D volume is present, the wheel steps frames
        instead). Starts from the window centre if no cursor has been set. When the
        step crosses the visible window edge, the window pans to follow the marker.

        Parameters
        ----------
        direction : number
        """
        self.send({"cmd": "stepSignalCursor", "args": _make_args(direction)})

    def swap_volume_chunk_plan(self, volume_id: Any, plan: Any) -> None:
        """Swap a loaded chunked/streamed volume's tiling plan in place (e.g.

        a
        multi-LOD refocus). Unchanged bricks keep their resident GPU textures; only
        changed/new bricks stream. Far cheaper than reloading the volume, and it
        doesn't reset the camera/crosshair. The volume must already be loaded with a
        `chunkSource`; otherwise this is a no-op.

        Parameters
        ----------
        volume_id : string
        plan : ChunkPlan
        """
        self.send({"cmd": "swapVolumeChunkPlan", "args": _make_args(volume_id, plan)})

    def update_gl_volume(self) -> None:
        self.send({"cmd": "updateGLVolume", "args": []})

    async def vox2frac(self, vox: Any) -> Any:
        """Convert RAS voxel coordinates to scene fraction [0,1].

        Uses the background volume's matRAS for the vox→mm conversion.

        Parameters
        ----------
        vox : [number, number, number]

        Returns
        -------
        [number, number, number]
        """
        return await self._request("vox2frac", _make_args(vox))


