import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const repositoryRoot = resolve(scriptDirectory, '../../..')
const mappingPath = resolve(scriptDirectory, 'about-author-name-map.json')
const outputPath = resolve(
  scriptDirectory,
  '../medgfx/AboutAuthors.generated.swift',
)

const authorNameMap = (await Bun.file(mappingPath).json()) as Record<
  string,
  string
>

const gitLog = Bun.spawnSync(
  ['git', 'log', '--reverse', '--format=%aN', '--', 'apps/medgfx'],
  {
    cwd: repositoryRoot,
    stderr: 'pipe',
    stdout: 'pipe',
  },
)

if (gitLog.exitCode !== 0) {
  throw new Error(
    gitLog.stderr.toString().trim() || 'Could not read Git history',
  )
}

const authors = gitLog.stdout
  .toString()
  .split('\n')
  .map((author) => author.trim())
  .filter((author) => author.length > 0)
  .map((author) => authorNameMap[author] ?? author)
  .filter((author, index, allAuthors) => allAuthors.indexOf(author) === index)

if (authors.length === 0) {
  throw new Error('No authors found in the Git history for apps/medgfx')
}

function swiftStringLiteral(value: string): string {
  const escaped = Array.from(value, (character) => {
    switch (character) {
      case '\\':
        return '\\\\'
      case '"':
        return '\\"'
      case '\n':
        return '\\n'
      case '\r':
        return '\\r'
      case '\t':
        return '\\t'
      default: {
        const codePoint = character.codePointAt(0)
        if (codePoint !== undefined && codePoint < 0x20) {
          return `\\u{${codePoint.toString(16)}}`
        }
        return character
      }
    }
  }).join('')

  return `"${escaped}"`
}

const authorLines = authors
  .map((author) => `        ${swiftStringLiteral(author)},`)
  .join('\n')

const generatedSource = `//
//  AboutAuthors.generated.swift
//  medgfx
//
//  Generated by scripts/generate-about-authors.ts. Do not edit directly.
//

enum MedgfxAboutAuthors {
    static let names = [
${authorLines}
    ]
}
`

await Bun.write(outputPath, generatedSource)
console.log(`Wrote ${authors.length} authors to ${outputPath}`)
