//
//  AboutAuthors.generated.swift
//  medgfx
//
//  Generated by scripts/generate-about-authors.ts. Do not edit directly.
//

enum MedgfxAboutAuthors {
    static let names = [
        "Taylor Hanayik",
        "Chris Rorden",
    ]
}
